version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "f3e0b86c68ec0ff6fb06137280115575c84d903f00e2b1c53382d1abdc9221037cc3834c3846a1ca0fe05820d60b202dce09a880fe05ce3728df2c2feb3337e0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb
    # command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Banguela153* # Altere para uma senha segura
      POSTGRES_DB: registro_poste_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
